### PR TITLE
Updated documentation figure

### PR DESCRIPTION
**Pull request by jdonkervliet**
Hi @binwiederhier, we updated a documentation figure, indicating the automated generation of SonarQube reports.

We were not sure about the subtitle of the image. What do you think?

### CODE REVIEW

**Comment by binwiederhier** [comment]
Awesome. Unfortunately, I updated the image for a presentation and forgot to re-upload it. I've uploaded the new version in this branch: https://github.com/syncany/syncany-assets/tree/continuous-integration-diverge

Maybe you can "merge" the two images?!? Sorry about that.

**Comment by cr0** [comment]
I agree, using "Original image" as a subtitle in Syncany's official repository seems wrong.

**Comment by jdonkervliet** [comment]
Yeah, I can make the sonar qube addition to the new image.

I agree on the name being not ideal. I didn't want to put my own name, but I also did not want to leave it unedited.

**Comment by binwiederhier** [comment]
Oh I completely missed that before. Just remove the name and leave the date. That's the most important part anyway.

**Comment by jdonkervliet** [comment]
Will do. Will be back with a new picture today or tomorrow. :smile:

**Pull request merged**
